name: MATLAB Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: matlab-actions/setup-matlab@v3
        with:
          cache: true
      - uses: matlab-actions/run-build@v3
      - uses: actions/upload-artifact@v7
        with:
          name: matstache-toolbox
          path: matstache.mltbx

  integration-test:
    needs: build
    if: github.event_name == 'push'
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        release: [R2024a, R2024b, R2025a, R2025b, R2026a]
        # TODO: Add back in 23a after fixing lambda tests to not
        # TODO: Add back in 23b after matlab-actions works again
        # use dictionary lookup
        # release: [R2023a, R2023b, R2024a, R2024b, R2025a, R2025b, R2026a]
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
          sparse-checkout: |
            tests
            .gitmodules
          sparse-checkout-cone-mode: false
      - uses: actions/download-artifact@v8
        with:
          name: matstache-toolbox
      - uses: matlab-actions/setup-matlab@v3
        with:
          release: ${{ matrix.release }}
      - name: Install toolbox
        uses: matlab-actions/run-command@v3
        with:
          command: matlab.addons.install("matstache.mltbx")
      - name: Run Tests
        uses: matlab-actions/run-tests@v3
