name: MATLAB Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: matlab-actions/setup-matlab@v3
        with:
          cache: true
      - uses: matlab-actions/run-build@v3
      - uses: actions/upload-artifact@v7
        with:
          name: matstache-toolbox
          path: matstache.mltbx

  integration-test:
    needs: build
    # if: github.event_name == 'push'
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        release: [R2024b, R2024a]
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
          sparse-checkout: |
            tests
            .gitmodules
          sparse-checkout-cone-mode: false
      - uses: actions/download-artifact@v8
        with:
          name: matstache-toolbox
      - uses: matlab-actions/setup-matlab@v3
        with:
          release: ${{ matrix.release }}
      - name: Install toolbox
        uses: matlab-actions/run-command@v3
        with:
          command: matlab.addons.install("matstache.mltbx", agreeToLicense)
      - name: Is toolbox here
        uses: matlab-actions/run-command@v3
        with:
          command: disp(matlab.addons.toolbox.installedToolboxes())
      - name: Is toolbox here
        uses: matlab-actions/run-command@v3
        with:
          command: path
      - name: Run Tests
        uses: matlab-actions/run-tests@v3
